name: Fist Maven Pipeline

# eventos que gatillan el workflow
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# trabajos
jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    container: maven:3.8.5-openjdk-17
    steps:
    - name: Update branch
      uses: actions/checkout@v5

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6
      with:
        name: artifact
        path: target/*.jar

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v5
